services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      TZ: Asia:Seoul
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - airflow-network
  
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: airflow
    user: "airflow:0"
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: ${AIRFLOW_UID}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "m8C8oCOLlhUHBYtLRGemJz0TBcxqGWduwEZkvxdS"
      TZ: Asia:Seoul
    ports:
      - "8081:8080"
    volumes:
        - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
        - /etc/localtime:/etc/localtime:ro
        - /Users/data-project/data-pipeline-project/airflow-project/airflow/modules:/opt/airflow/modules
        - /Users/data-project/data-pipeline-project/airflow-project/spark:/opt/spark
        - /Users/data-project/data-pipeline-project/airflow-project/shared:/shared
        - /Users/data-project/data-pipeline-project:/opt/airflow/data-pipeline-project
        - /Users/data-project/data-pipeline-project/airflow-project/shared/data/brands_test.json:/opt/airflow/data/brands_test.json
        - ./output:/opt/airflow/output
    networks:
      - airflow-network
    command: ["airflow", "webserver"]
    
  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: airflow
    user: "${AIRFLOW_UID}:0"
    restart: always
    depends_on:
      - postgres
      - webserver
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: ${AIRFLOW_UID}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "m8C8oCOLlhUHBYtLRGemJz0TBcxqGWduwEZkvxdS"
      PATH: $PATH:/home/airflow/.local/bin
      TZ: Asia:Seoul
    volumes:
        - /Users/data-project/data-pipeline-project/airflow-project/shared:/shared
        - /Users/data-project/data-pipeline-project/airflow-project/shared/data/brands_test.json:/opt/airflow/data/brands_test.json
        - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
        - /etc/localtime:/etc/localtime:ro
        - /Users/data-project/data-pipeline-project:/opt/airflow/data-pipeline-project
        - /Users/data-project/data-pipeline-project/airflow-project/airflow/modules:/opt/airflow/modules
        - /Users/data-project/data-pipeline-project/airflow-project/airflow/dags:/opt/airflow/dags
        - ./output:/opt/airflow/output
    networks:
      - airflow-network
    command: scheduler

volumes:
  postgres-db-volume:

networks:
  airflow-network:
    driver: bridge